export {default as Navbar} from './navbar/Navbar'
export {default as Footer} from './footer/Footer'
export {default as FAQ} from './faq/FAQ'
export {default as Contact_us} from './contactus/Contact_us'
export {default as Animation} from './animation/Animation'
export {default as About_us} from './aboutus/About_us'